server:
  port: 8082

spring:
  data:
    mongodb:
      # Para docker:
      # uri: mongodb://host.docker.internal:27017/db_account
      # Local
      uri: mongodb://localhost:27017/db_account

external:
  services:
    customer:
      url: http://localhost:8081
    credit:
      url: http://localhost:8083

logging:
  level:
    root: INFO
    com.bank.account: DEBUG
    
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,beans
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
    info:
      enabled: true
  info:
    env:
      enabled: true
    build:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    version: 1.0
    description: Microservice for bank account management
    
# Configuración de Eureka - AGREGAR ESTO
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: false
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}