server:
  port: 8079

spring:
  application:
    name: api-gateway-service

  security:
    jwt:
      secret-key: "BankApp2025!SuperSecureJWTKey@256BitsForMicroservicesGateway#SpringBoot3"
      expiration-time: 86400000

  app:
    users:
      - username: "admin"
        password: "admin123"
        roles:
          - "ROLE_ADMIN"
          - "ROLE_USER"
      - username: "user"
        password: "user123"
        roles:
          - "ROLE_USER"
      - username: "operator"
        password: "operator123"
        roles:
          - "ROLE_OPERATOR"

  cloud:
    gateway:
      routes:
        # Customer Service Route - CON JWT
        - id: customer-service
          uri: http://host.docker.internal:8081
          predicates:
            - Path=/api/customers/**
          filters:
            - RewritePath=/api/customers/?(?<segment>.*), /customers/${segment}
            - name: JwtAuthenticationFilter
            - name: CircuitBreaker
              args:
                name: customerService
                fallbackUri: forward:/fallback/customer

        # Account Service Route - CON JWT
        - id: account-service
          uri: http://host.docker.internal:8082
          predicates:
            - Path=/api/accounts/**
          filters:
            - RewritePath=/api/accounts/?(?<segment>.*), /accounts/${segment}
            - name: JwtAuthenticationFilter
            - name: CircuitBreaker
              args:
                name: accountService
                fallbackUri: forward:/fallback/account

        # Credit Service Route - CON JWT
        - id: credit-service
          uri: http://host.docker.internal:8083
          predicates:
            - Path=/api/credits/**
          filters:
            - RewritePath=/api/credits/?(?<segment>.*), /credits/${segment}
            - name: JwtAuthenticationFilter
            - name: CircuitBreaker
              args:
                name: creditService
                fallbackUri: forward:/fallback/credit

        # Transaction Service Route - CON JWT
        - id: transaction-service
          uri: http://host.docker.internal:8084
          predicates:
            - Path=/api/transactions/**
          filters:
            - RewritePath=/api/transactions/?(?<segment>.*), /transactions/${segment}
            - name: JwtAuthenticationFilter
            - name: CircuitBreaker
              args:
                name: transactionService
                fallbackUri: forward:/fallback/transaction

      # Discovery dinámico DESHABILITADO (usando rutas estáticas con JWT)
      discovery:
        locator:
          enabled: false

      # Configuración de HTTP Client
      httpclient:
        connect-timeout: 2000
        response-timeout: 10s
        pool:
          max-connections: 1000
          max-idle-time: 30000

    # Config Client (usa host.docker.internal dentro del contenedor)
    config:
      uri: http://host.docker.internal:8888
      fail-fast: false

  # Circuit Breaker Configuration
  resilience4j:
    circuitbreaker:
      configs:
        default:
          slidingWindowSize: 10
          failureRateThreshold: 50
          waitDurationInOpenState: 10000
          permittedNumberOfCallsInHalfOpenState: 3
          automaticTransitionFromOpenToHalfOpenEnabled: true
      instances:
        customerService:
          baseConfig: default
        accountService:
          baseConfig: default
        creditService:
          baseConfig: default
        transactionService:
          baseConfig: default

# Eureka Client Configuration DESHABILITADO
eureka:
  client:
    enabled: false

# Actuator Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,metrics,env
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
    gateway:
      enabled: true
    info:
      enabled: true
  info:
    env:
      enabled: true
    build:
      enabled: true

# Información de la aplicación
info:
  app:
    name: ${spring.application.name}
    description: API Gateway for Bank Microservices System (Docker with JWT)
    version: 1.0.0
    environment: docker

# Logging
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG
    com.bank.gateway: INFO