server:
  port: 8079

spring:
  application:
    name: api-gateway-service
  security:
    jwt:
      secret-key: "BankApp2025!SuperSecureJWTKey@256BitsForMicroservicesGateway#SpringBoot3"
      expiration-time: 86400000

  app:
    users:
      - username: "admin"
        password: "admin123"
        roles:
          - "ROLE_ADMIN"
          - "ROLE_USER"
      - username: "user"
        password: "user123"
        roles:
          - "ROLE_USER"
      - username: "operator"
        password: "operator123"
        roles:
          - "ROLE_OPERATOR"

  cloud:
    gateway:
      routes:
        # Auth Service Route - SIN JWT (público)
        - id: auth-service
          uri: http://localhost:8079  # Apunta al mismo gateway para el auth
          predicates:
            - Path=/api/auth/**
          filters:
            - name: JwtAuthenticationFilter
              args:
                skip: true  # Saltar JWT para endpoints de auth

        # Customer Service Route - CON JWT
        - id: customer-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/customers/**
          filters:
            - RewritePath=/api/customers/?(?<segment>.*), /customers/$\{segment}
            - name: JwtAuthenticationFilter  # AGREGAR ESTE FILTRO
            - name: CircuitBreaker
              args:
                name: customerService
                fallbackUri: forward:/fallback/customer

        # Account Service Route - CON JWT
        - id: account-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/accounts/**
          filters:
            - RewritePath=/api/accounts/?(?<segment>.*), /accounts/$\{segment}
            - name: JwtAuthenticationFilter  # AGREGAR ESTE FILTRO
            - name: CircuitBreaker
              args:
                name: accountService
                fallbackUri: forward:/fallback/account

        # Credit Service Route - CON JWT
        - id: credit-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/credits/**
          filters:
            - RewritePath=/api/credits/?(?<segment>.*), /credits/$\{segment}
            - name: JwtAuthenticationFilter  # AGREGAR ESTE FILTRO
            - name: CircuitBreaker
              args:
                name: creditService
                fallbackUri: forward:/fallback/credit

        # Transaction Service Route - CON JWT
        - id: transaction-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/transactions/**
          filters:
            - RewritePath=/api/transactions/?(?<segment>.*), /transactions/$\{segment}
            - name: JwtAuthenticationFilter  # AGREGAR ESTE FILTRO
            - name: CircuitBreaker
              args:
                name: transactionService
                fallbackUri: forward:/fallback/transaction

      discovery:
        locator:
          enabled: false
          
      httpclient:
        connect-timeout: 2000
        response-timeout: 10s

    config:
      uri: http://localhost:8888
      fail-fast: false

# El resto de la configuración permanece igual...
resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
    instances:
      customerService:
        baseConfig: default
      accountService:
        baseConfig: default  
      creditService:
        baseConfig: default
      transactionService:
        baseConfig: default

eureka:
  client:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,metrics,env
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    description: API Gateway for Bank Microservices System
    version: 1.0.0

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG
    com.bank.gateway: INFO