server:
  port: 8086

spring:
  application:
    name: bootcoin-service  # ← AGREGAR ESTO
  
  data:
    mongodb:
      # Para docker:
      # uri: mongodb://host.docker.internal:27017/bootcoin
      # Local
      uri: mongodb://localhost:27017/bootcoin
      
  # CONFIGURACIÓN KAFKA - AGREGAR ESTO
  kafka:
    bootstrap-servers: localhost:29093  # ← Cambiar a puerto estándar
    consumer:
      group-id: bootcoin-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "com.bank.bootcoin.application.event,com.bank.yanki.application.event"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        spring.json.add.type.headers: false
    properties:
      security.protocol: PLAINTEXT

# CONFIGURACIÓN KAFKA TOPICS - AGREGAR ESTO
app:
  kafka:
    topics:
      bootcoin-transactions: bootcoin-transactions
      yanki-payments: yanki-payments
      account-transactions: account-transactions
      wallet-updates: wallet-updates
      balance-validation-request: balance-validation-request
      balance-validation-response: balance-validation-response
      yanki-balance-validation-request: yanki-balance-validation-request
      yanki-balance-validation-response: yanki-balance-validation-response

# SERVICIOS EXTERNOS - AGREGAR ESTO
external:
  services:
    yanki:
      url: http://localhost:8085
    account:
      url: http://localhost:8082
    credit:
      url: http://localhost:8083

logging:
  level:
    root: INFO
    com.bank.bootcoin: DEBUG
    org.springframework.kafka: INFO  # ← AGREGAR PARA DEBUG KAFKA
    
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,beans
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
    info:
      enabled: true
  info:
    env:
      enabled: true
    build:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    version: 1.0
    description: Bootcoin Service for Bank System at NTT DATA
    
# Configuración de Eureka - ACTUALIZAR ESTO
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:  # ← AGREGAR ESTO
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: false
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}