server:
  port: 8083

spring:
  data:
    mongodb:
      # Para docker:
      # uri: mongodb://host.docker.internal:27017/db_credit
      # Local
      uri: mongodb://localhost:27017/db_credit

logging:
  level:
    root: INFO
    com.bank.credit: DEBUG
    
 springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    url: /openapi/credit-api.yaml