server:
  port: 8083

spring:
  application:
    name: credit-service
  data:
    mongodb:
      uri: mongodb://mongodb:27017/db_credit
  kafka:
    bootstrap-servers: yanki-service-kafka-1:9092
    consumer:
      group-id: credit-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    properties:
      security.protocol: PLAINTEXT

app:
  kafka:
    topics:
      credit-balance-inquiry: yanki.credit.balance.inquiry
      credit-balance-response: yanki.credit.balance.response

external:
  services:
    customer:
      url: ${EXTERNAL_SERVICES_CUSTOMER_URL:http://customer-service:8081}
    account:
      url: ${EXTERNAL_SERVICES_ACCOUNT_URL:http://account-service:8082}
    transaction:
      url: ${EXTERNAL_SERVICES_TRANSACTION_URL:http://transaction-service:8084}

logging:
  level:
    root: INFO
    com.bank.credit: DEBUG
    org.springframework.kafka: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,beans
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
    info:
      enabled: true
  info:
    env:
      enabled: true
    build:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    version: 1.0
    description: Microservice for bank credit management

# Configuración de Eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URI:http://eureka-server:8761/eureka}
  instance:
    prefer-ip-address: false
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}
    non-secure-port: ${server.port}
    home-page-url: http://localhost:${server.port}
    health-check-url: http://localhost:${server.port}/actuator/health
    status-page-url: http://localhost:${server.port}/actuator/info