server:
  port: 8081

spring:
  data:
    mongodb:
      # Para docker:
      # uri: mongodb://host.docker.internal:27017/db_customer
      # Local
      uri: mongodb://localhost:27017/db_customer

logging:
  level:
    root: INFO
    com.bank.customer: DEBUG
    
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,beans
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
    info:
      enabled: true
  info:
    env:
      enabled: true
    build:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    version: ${project.version}
    description: ${spring.application.description}