spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27017/db_transaction

external:
  services:
    account:
      url: http://host.docker.internal:8082
    credit:
      url: http://host.docker.internal:8083

logging:
  level:
    com.bank.transaction: DEBUG