server:
  port: 8084

spring:
  data:
    mongodb:
      # Para docker:
      # uri: mongodb://host.docker.internal:27017/db_transaction
      # Local
      uri: mongodb://localhost:27017/db_transaction

external:
  services:
    account:
      url: http://localhost:8082
    credit:
      url: http://localhost:8083

logging:
  level:
    root: INFO
    com.bank.credit: DEBUG