server:
  port: 8084

spring:
  application:
    name: transaction-service
  data:
    mongodb:
      uri: mongodb://mongodb:27017/db_transaction
  kafka:
    bootstrap-servers: yanki-service-kafka-1:9092
    consumer:
      group-id: transaction-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "com.bank.yanki.application.event,com.bank.yanki.domain.model"
        spring.json.use.type.headers: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    properties:
      security.protocol: PLAINTEXT

app:
  kafka:
    topics:
      transaction-payment-request: transaction.payment.request
      transaction-consumption-request: transaction.consumption.request
      bank-withdrawal-request: bank-withdrawal-request
      bank-withdrawal-response: bank-withdrawal-response

external:
  services:
    account:
      url: ${EXTERNAL_SERVICES_ACCOUNT_URL:http://account-service:8082}
    credit:
      url: ${EXTERNAL_SERVICES_CREDIT_URL:http://credit-service:8083}

logging:
  level:
    root: INFO
    com.bank.transaction: DEBUG
    org.springframework.kafka: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,beans
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
    info:
      enabled: true
  info:
    env:
      enabled: true
    build:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    version: 1.0
    description: Microservice for bank transaction management

# Configuración de Eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URI:http://eureka-server:8761/eureka}
  instance:
    prefer-ip-address: false
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}
    non-secure-port: ${server.port}
    home-page-url: http://localhost:${server.port}
    health-check-url: http://localhost:${server.port}/actuator/health
    status-page-url: http://localhost:${server.port}/actuator/info