server:
  port: 8082

spring:
  data:
    mongodb:
      # Para docker:
      # uri: mongodb://host.docker.internal:27017/db_account
      # Local
      uri: mongodb://localhost:27017/db_account

logging:
  level:
    root: INFO
    com.bank.customer: DEBUG